# Notes
# To run one instance of zk, kafka and the registry service:
# - $ docker-compose up [-d]
#
# To run the tests (one-off; does not require a previous docker-compose up):
# - $ docker-compose run --rm --name registry_test registry go test -v ./...
#
# To run 3 instances of kafka, and 1 instance of zk and the registry:
# - $ docker-compose up --scale kafka=3
#
# To query the registry:
#  - $ curl -s $(docker-machine ip):8080/v1/topics/list | jq

version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:${KAFKA_VERSION:-2.11-0.10.2.2}
    ports:
      - "9092"
      - "9093"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "docker-machine ip 2>/dev/null || echo 0.0.0.0"
      PORT_COMMAND: "docker port $$(hostname) 9093/tcp | cut -d: -f2"
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://_{HOSTNAME_COMMAND}:_{PORT_COMMAND}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test1:1:3,test2:2:2"
      KAFKA_BROKER_RACK: 1a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    build:
      context: .
      dockerfile: Dockerfile.registry
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - zookeeper
      - kafka
    environment:
      TEST_ZK_ADDR: zookeeper:2181
      REGISTRY_ZK_ADDR: zookeeper:2181
      REGISTRY_BOOTSTRAP_SERVERS: kafka:9092
      REGISTRY_HTTP_LISTEN: 0.0.0.0:8080
      REGISTRY_GRPC_LISTEN: 0.0.0.0:8090
